#spring:
#  jpa:
#    hibernate:
#      #     更新或者创建数据表结构
#      ddl-auto: update
#      naming:
#        physicalstrategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        #    控制台显示SQL
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect